[application]

[desktop]
# Minimum window size
width = "1280px"
height = "720px"

[web.app]

# HTML title tag content
title = "GTLLM"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.chironjit.gtllm"
publisher = "Chironjit Das"


